In [9]:
import numpy as np
import pandas as pd
from hmmlearn import hmm

In [5]:
# 读取数据
filepath = "raw_price_train/1_r_price_train.csv"
data = pd.read_csv(filepath)
data.head()

Date       Open       High        Low      Close  Adj Close     Volume
0   2012/9/4  95.108574  96.448570  94.928574  96.424286  87.121140   91973000
1   2012/9/5  96.510002  96.621429  95.657143  95.747147  86.509338   84093800
2   2012/9/6  96.167145  96.898575  95.828575  96.610001  87.288956   97799100
3   2012/9/7  96.864288  97.497147  96.538574  97.205711  87.827171   82416600
4  2012/9/10  97.207146  97.612854  94.585716  94.677139  85.542564  121999500

In [8]:
close = data["Adj Close"].values

In [14]:
close = close.reshape(-1,1)

In [15]:
close

array([[ 87.12114 ],
       [ 86.509338],
       [ 87.288956],
       [ 87.827171],
       [ 85.542564],
       [ 85.265068],
       [ 86.452538],
       [ 88.155037],
       [ 89.226341],
       [ 90.323479],
       [ 90.598404],
       [ 90.622932],
       [ 90.18409 ],
       [ 90.363457],
       [ 89.163078],
       [ 86.936554],
       [ 85.857506],
       [ 87.94075 ],
       [ 86.105347],
       [ 85.110161],
       [ 85.358002],
       [ 86.666817],
       [ 86.066612],
       [ 84.23246 ],
       [ 82.371223],
       [ 82.071747],
       [ 82.724876],
       [ 81.071426],
       [ 81.279243],
       [ 81.931084],
       [ 83.871056],
       [ 83.202446],
       [ 81.657455],
       [ 78.714554],
       [ 81.836838],
       [ 79.168869],
       [ 79.616783],
       [ 78.675812],
       [ 77.960747],
       [ 76.840401],
       [ 76.997864],
       [ 74.449928],
       [ 75.45929 ],
       [ 75.230835],
       [ 72.35231 ],
       [ 69.726601],
       [ 70.933784],
       [ 70.3

In [16]:
n = 5
model = hmm.GaussianHMM(n_components=n,n_iter=2000).fit(close)

In [19]:
hidden_states = model.predict(close[-5:])

In [22]:
model.transmat_

array([[9.88007782e-001, 1.12705546e-134, 1.58381209e-049,
        5.99547144e-003, 5.99674639e-003],
       [5.46426274e-080, 9.91361725e-001, 0.00000000e+000,
        8.63827451e-003, 0.00000000e+000],
       [9.54689174e-048, 0.00000000e+000, 9.94666959e-001,
        0.00000000e+000, 5.33304148e-003],
       [5.15671854e-040, 6.01752059e-003, 1.43536586e-206,
        9.93982479e-001, 2.55268872e-158],
       [5.50406341e-003, 0.00000000e+000, 5.59214662e-003,
        8.56125093e-214, 9.88903790e-001]])

In [21]:
close[-5:]
#Hmmlearn 只能构建简单的马尔可夫过程

array([[108.679771],
       [106.756989],
       [107.57827 ],
       [105.298019],
       [102.44767 ]])